# Generated by Django 3.0.3 on 2020-04-17 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluation', '0001_initial'),
        ('evaluationtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_evaluation', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('eleves', models.ManyToManyField(related_name='eleves', to=settings.AUTH_USER_MODEL)),
                ('evaluateurs', models.ManyToManyField(related_name='evaluateurs', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ManyToManyField(blank=True, related_name='notes', to='evaluation.Note')),
                ('responsable_parcours', models.ManyToManyField(related_name='reponsable_parcours', to=settings.AUTH_USER_MODEL)),
                ('type_evaluation', models.ManyToManyField(related_name='type_evaluation', to='evaluationtype.EvaluationType')),
            ],
        ),
    ]
