# Generated by Django 3.0.3 on 2020-04-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_evaluationtype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField(blank=True, default=0)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Critere')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationtype.EvaluationType')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='criteres',
            field=models.ManyToManyField(related_name='criteres', through='evaluationtype.Poids', to='criterion.Critere'),
        ),
    ]
